[uwsgi]

chdir = /home/rmueller/fewo-calserver

module = wsgi
callable = application

master = true
processes = 5

# the fix
lazy = true
lazy-apps = true

socket = /tmp/flaskr.sock
chmod-socket = 666
vacuum = true

# os writer error

ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true

# logging

log-5xx = true
disable-logging = true
~                             
